
version: '2'
services:
  jenkins:
    image: 'bitnami/jenkins:2'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    environment:
      - DISABLE_JENKINS_INITIALIZATION=yes
    volumes:
      - 'jenkins_data:/bitnami'
    networks:
      - demo
  sonarqube:
    image: "sonarqube"
    ports:
     - "9000:9000"
    networks:
      - demo
  tomcat:
    image: 'tutum/tomcat:6.0'
    ports:
      - 10000:8080
    environment:
      - TOMCAT_PASS=admin
    networks:
      - demo
volumes:
  jenkins_data:
    driver: local
networks:
  demo:
